// Seed data for Thailand Expenses Tracker
// Generated from the user's Excel sheet (May 7 - May 16, 2026)
window.SEED_DATA = {
  "expenses": [
    {
      "id": 1000,
      "expense_date": "2026-05-07",
      "amount": 350,
      "description": "Grab from Airport to Condo",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1001,
      "expense_date": "2026-05-07",
      "amount": 100,
      "description": "Grab ride",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1002,
      "expense_date": "2026-05-07",
      "amount": 100,
      "description": "Grab ride",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1003,
      "expense_date": "2026-05-07",
      "amount": 100,
      "description": "Grab ride",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1004,
      "expense_date": "2026-05-07",
      "amount": 66.67,
      "description": "Grab ride",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1005,
      "expense_date": "2026-05-07",
      "amount": 66.67,
      "description": "Grab ride",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1006,
      "expense_date": "2026-05-07",
      "amount": 66.67,
      "description": "Grab ride",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1007,
      "expense_date": "2026-05-07",
      "amount": 7.33,
      "description": "Water",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1008,
      "expense_date": "2026-05-07",
      "amount": 7.33,
      "description": "Water",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "PENDING",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1009,
      "expense_date": "2026-05-07",
      "amount": 7.33,
      "description": "Water",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1010,
      "expense_date": "2026-05-07",
      "amount": 17,
      "description": "Grab ride",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 1011,
      "expense_date": "2026-05-08",
      "amount": 60,
      "description": "Bawang dll",
      "toko": "Grab",
      "source": "Winda Cash",
      "category": "Transport",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 1012,
      "expense_date": "2026-05-08",
      "amount": 32,
      "description": "Lays",
      "toko": "Seven 11",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 1013,
      "expense_date": "2026-05-08",
      "amount": 10,
      "description": "7-Eleven snacks",
      "toko": "Seven 11",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "REJECTED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 1014,
      "expense_date": "2026-05-08",
      "amount": 10,
      "description": "7-Eleven snacks",
      "toko": "Seven 11",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 1015,
      "expense_date": "2026-05-08",
      "amount": 10,
      "description": "7-Eleven snacks",
      "toko": "Seven 11",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 1016,
      "expense_date": "2026-05-08",
      "amount": 16.33,
      "description": "spicy seaweed snack",
      "toko": "Seven 11",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 1017,
      "expense_date": "2026-05-08",
      "amount": 16.33,
      "description": "spicy seaweed snack",
      "toko": "Seven 11",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 1018,
      "expense_date": "2026-05-08",
      "amount": 16.33,
      "description": "spicy seaweed snack",
      "toko": "Seven 11",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "REJECTED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 1019,
      "expense_date": "2026-05-09",
      "amount": 16.33,
      "description": "7-Eleven snacks",
      "toko": "Seven 11",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1020,
      "expense_date": "2026-05-09",
      "amount": 16.33,
      "description": "7-Eleven snacks",
      "toko": "Seven 11",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1021,
      "expense_date": "2026-05-09",
      "amount": 16.33,
      "description": "7-Eleven snacks",
      "toko": "Seven 11",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1022,
      "expense_date": "2026-05-09",
      "amount": 63.25,
      "description": "Chicken Upper Wings (per kg)",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1023,
      "expense_date": "2026-05-09",
      "amount": 35,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1024,
      "expense_date": "2026-05-09",
      "amount": 34.5,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1025,
      "expense_date": "2026-05-09",
      "amount": 57,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1026,
      "expense_date": "2026-05-09",
      "amount": 115,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1027,
      "expense_date": "2026-05-09",
      "amount": 199,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1028,
      "expense_date": "2026-05-09",
      "amount": 60,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1029,
      "expense_date": "2026-05-09",
      "amount": 199,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1030,
      "expense_date": "2026-05-09",
      "amount": 49,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1031,
      "expense_date": "2026-05-09",
      "amount": 40,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1032,
      "expense_date": "2026-05-09",
      "amount": 38,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1033,
      "expense_date": "2026-05-09",
      "amount": 69,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1034,
      "expense_date": "2026-05-09",
      "amount": 51,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1035,
      "expense_date": "2026-05-09",
      "amount": 29,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1036,
      "expense_date": "2026-05-09",
      "amount": 34,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "REJECTED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1037,
      "expense_date": "2026-05-09",
      "amount": 29,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1038,
      "expense_date": "2026-05-09",
      "amount": 43,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1039,
      "expense_date": "2026-05-09",
      "amount": 105,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1040,
      "expense_date": "2026-05-09",
      "amount": 25.5,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1041,
      "expense_date": "2026-05-09",
      "amount": 118,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1042,
      "expense_date": "2026-05-09",
      "amount": 36,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1043,
      "expense_date": "2026-05-09",
      "amount": 11.5,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1044,
      "expense_date": "2026-05-09",
      "amount": 80,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1045,
      "expense_date": "2026-05-09",
      "amount": 9.5,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1046,
      "expense_date": "2026-05-09",
      "amount": 24.5,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1047,
      "expense_date": "2026-05-09",
      "amount": 24.5,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1048,
      "expense_date": "2026-05-09",
      "amount": 48.5,
      "description": "Makro groceries",
      "toko": "Makro",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 1049,
      "expense_date": "2026-05-10",
      "amount": 22,
      "description": "Vixol Sunny Fresh (700ml)",
      "toko": "Lotus",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 1050,
      "expense_date": "2026-05-10",
      "amount": 40,
      "description": "Lotus groceries",
      "toko": "Lotus",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 1051,
      "expense_date": "2026-05-10",
      "amount": 48,
      "description": "Lotus groceries",
      "toko": "Lotus",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 1052,
      "expense_date": "2026-05-10",
      "amount": 40,
      "description": "Lotus groceries",
      "toko": "Lotus",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 1053,
      "expense_date": "2026-05-10",
      "amount": 29,
      "description": "Lotus groceries",
      "toko": "Lotus",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 1054,
      "expense_date": "2026-05-10",
      "amount": 44,
      "description": "Lotus groceries",
      "toko": "Lotus",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "REJECTED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 1055,
      "expense_date": "2026-05-10",
      "amount": 9,
      "description": "Lotus groceries",
      "toko": "Lotus",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 1056,
      "expense_date": "2026-05-10",
      "amount": 37.5,
      "description": "Lotus groceries",
      "toko": "Lotus",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 1057,
      "expense_date": "2026-05-10",
      "amount": 38,
      "description": "Lotus groceries",
      "toko": "Lotus",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 1058,
      "expense_date": "2026-05-12",
      "amount": 32,
      "description": "Lotus groceries",
      "toko": "Lotus",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1059,
      "expense_date": "2026-05-12",
      "amount": 333.33,
      "description": "Topup at 7-Eleven",
      "toko": "71",
      "source": "Winda Cash",
      "category": "Other",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "REJECTED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1060,
      "expense_date": "2026-05-12",
      "amount": 333.33,
      "description": "Topup at 7-Eleven",
      "toko": "71",
      "source": "Winda Cash",
      "category": "Other",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1061,
      "expense_date": "2026-05-12",
      "amount": 333.33,
      "description": "Topup at 7-Eleven",
      "toko": "71",
      "source": "Winda Cash",
      "category": "Other",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1062,
      "expense_date": "2026-05-12",
      "amount": 55,
      "description": "Smoothies",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1063,
      "expense_date": "2026-05-12",
      "amount": 40,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1064,
      "expense_date": "2026-05-12",
      "amount": 8,
      "description": "Wai Wai High Fiber Rice Vermicelli",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1065,
      "expense_date": "2026-05-12",
      "amount": 8,
      "description": "Wai Wai High Fiber Rice Vermicelli",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1066,
      "expense_date": "2026-05-12",
      "amount": 8,
      "description": "Wai Wai High Fiber Rice Vermicelli",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1067,
      "expense_date": "2026-05-12",
      "amount": 10.83,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "PENDING",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1068,
      "expense_date": "2026-05-12",
      "amount": 10.83,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1069,
      "expense_date": "2026-05-12",
      "amount": 10.83,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1070,
      "expense_date": "2026-05-12",
      "amount": 13,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1071,
      "expense_date": "2026-05-12",
      "amount": 13,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1072,
      "expense_date": "2026-05-12",
      "amount": 13,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "PENDING",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1073,
      "expense_date": "2026-05-12",
      "amount": 38.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1074,
      "expense_date": "2026-05-12",
      "amount": 38.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1075,
      "expense_date": "2026-05-12",
      "amount": 38.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1076,
      "expense_date": "2026-05-12",
      "amount": 59,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1077,
      "expense_date": "2026-05-12",
      "amount": 30,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "REJECTED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1078,
      "expense_date": "2026-05-12",
      "amount": 24,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1079,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1080,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1081,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1082,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1083,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1084,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1085,
      "expense_date": "2026-05-12",
      "amount": 26,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "PENDING",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1086,
      "expense_date": "2026-05-12",
      "amount": 26,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1087,
      "expense_date": "2026-05-12",
      "amount": 26,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1088,
      "expense_date": "2026-05-12",
      "amount": 10,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1089,
      "expense_date": "2026-05-12",
      "amount": 10,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1090,
      "expense_date": "2026-05-12",
      "amount": 10,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "PENDING",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1091,
      "expense_date": "2026-05-12",
      "amount": 89,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1092,
      "expense_date": "2026-05-12",
      "amount": 20,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1093,
      "expense_date": "2026-05-12",
      "amount": 11.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1094,
      "expense_date": "2026-05-12",
      "amount": 11.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1095,
      "expense_date": "2026-05-12",
      "amount": 11.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "REJECTED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1096,
      "expense_date": "2026-05-12",
      "amount": 21,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1097,
      "expense_date": "2026-05-12",
      "amount": 10.25,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1098,
      "expense_date": "2026-05-12",
      "amount": 11.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1099,
      "expense_date": "2026-05-12",
      "amount": 11.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1100,
      "expense_date": "2026-05-12",
      "amount": 11.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1101,
      "expense_date": "2026-05-12",
      "amount": 23,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1102,
      "expense_date": "2026-05-12",
      "amount": 12.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1103,
      "expense_date": "2026-05-12",
      "amount": 12.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1104,
      "expense_date": "2026-05-12",
      "amount": 12.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1105,
      "expense_date": "2026-05-12",
      "amount": 13.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1106,
      "expense_date": "2026-05-12",
      "amount": 13.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1107,
      "expense_date": "2026-05-12",
      "amount": 13.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1108,
      "expense_date": "2026-05-12",
      "amount": 12.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "PENDING",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1109,
      "expense_date": "2026-05-12",
      "amount": 12.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1110,
      "expense_date": "2026-05-12",
      "amount": 12.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1111,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1112,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1113,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "REJECTED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1114,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1115,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1116,
      "expense_date": "2026-05-12",
      "amount": 5,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1117,
      "expense_date": "2026-05-12",
      "amount": 20,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1118,
      "expense_date": "2026-05-12",
      "amount": 134,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "REJECTED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1119,
      "expense_date": "2026-05-12",
      "amount": 25,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1120,
      "expense_date": "2026-05-12",
      "amount": 25,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1121,
      "expense_date": "2026-05-12",
      "amount": 25,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1122,
      "expense_date": "2026-05-12",
      "amount": 15,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1123,
      "expense_date": "2026-05-12",
      "amount": 15,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1124,
      "expense_date": "2026-05-12",
      "amount": 15,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1125,
      "expense_date": "2026-05-12",
      "amount": 21.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1126,
      "expense_date": "2026-05-12",
      "amount": 21.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "PENDING",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1127,
      "expense_date": "2026-05-12",
      "amount": 21.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1128,
      "expense_date": "2026-05-12",
      "amount": 21.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1129,
      "expense_date": "2026-05-12",
      "amount": 21.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1130,
      "expense_date": "2026-05-12",
      "amount": 21.67,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1131,
      "expense_date": "2026-05-12",
      "amount": 10,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1132,
      "expense_date": "2026-05-12",
      "amount": 8,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1133,
      "expense_date": "2026-05-12",
      "amount": 8,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1134,
      "expense_date": "2026-05-12",
      "amount": 8,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1135,
      "expense_date": "2026-05-12",
      "amount": 16.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1136,
      "expense_date": "2026-05-12",
      "amount": 16.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "REJECTED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1137,
      "expense_date": "2026-05-12",
      "amount": 16.33,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1138,
      "expense_date": "2026-05-12",
      "amount": 125,
      "description": "Café items",
      "toko": "Caffee",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 1139,
      "expense_date": "2026-05-15",
      "amount": 37.5,
      "description": "Water",
      "toko": "Water",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-15T18:00:00Z"
    },
    {
      "id": 1140,
      "expense_date": "2026-05-15",
      "amount": 137,
      "description": "Eggtart and chicken",
      "toko": "KFC",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-15T18:00:00Z"
    },
    {
      "id": 1141,
      "expense_date": "2026-05-16",
      "amount": 25,
      "description": "Wortel",
      "toko": "KFC",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1142,
      "expense_date": "2026-05-16",
      "amount": 20,
      "description": "Pepsi",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1143,
      "expense_date": "2026-05-16",
      "amount": 19,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1144,
      "expense_date": "2026-05-16",
      "amount": 55,
      "description": "bubble latte",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1145,
      "expense_date": "2026-05-16",
      "amount": 210,
      "description": "Berlima",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1146,
      "expense_date": "2026-05-16",
      "amount": 168,
      "description": "Berempat",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1147,
      "expense_date": "2026-05-16",
      "amount": 50,
      "description": "Berlima",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1148,
      "expense_date": "2026-05-16",
      "amount": 75,
      "description": "Gorengan manis 3 jenis",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1149,
      "expense_date": "2026-05-16",
      "amount": 20,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1150,
      "expense_date": "2026-05-16",
      "amount": 20,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1151,
      "expense_date": "2026-05-16",
      "amount": 35,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1152,
      "expense_date": "2026-05-16",
      "amount": 60,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1153,
      "expense_date": "2026-05-16",
      "amount": 35,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1154,
      "expense_date": "2026-05-16",
      "amount": 55,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1155,
      "expense_date": "2026-05-16",
      "amount": 11,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": false,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1156,
      "expense_date": "2026-05-16",
      "amount": 3.67,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": true,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1157,
      "expense_date": "2026-05-16",
      "amount": 3.67,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Winda",
      "shared": true,
      "status": "APPROVED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1158,
      "expense_date": "2026-05-16",
      "amount": 3.67,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Syaeful",
      "shared": true,
      "status": "PENDING",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 1159,
      "expense_date": "2026-05-16",
      "amount": 332,
      "description": "Tops supermarket",
      "toko": "Tops",
      "source": "Winda Cash",
      "category": "Food",
      "attachment_path": null,
      "recorder": "Dina",
      "shared": false,
      "status": "APPROVED",
      "created_at": "2026-05-16T18:00:00Z"
    }
  ],
  "loans": [
    {
      "id": 5000,
      "expense_id": 1000,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 350,
      "declared_repayment": 350,
      "actual_repaid": 350,
      "remaining_balance": 0,
      "status": "FULLY_SETTLED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 5001,
      "expense_id": 1001,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 100,
      "declared_repayment": 100,
      "actual_repaid": 50,
      "remaining_balance": 50,
      "status": "PARTIAL",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 5002,
      "expense_id": 1003,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 100,
      "declared_repayment": 100,
      "actual_repaid": 0,
      "remaining_balance": 100,
      "status": "UNSETTLED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 5003,
      "expense_id": 1004,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 66.67,
      "declared_repayment": 66.67,
      "actual_repaid": 66.67,
      "remaining_balance": 0,
      "status": "FULLY_SETTLED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 5004,
      "expense_id": 1006,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 66.67,
      "declared_repayment": 66.67,
      "actual_repaid": 0,
      "remaining_balance": 66.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 5005,
      "expense_id": 1007,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 7.33,
      "declared_repayment": 7.33,
      "actual_repaid": 0,
      "remaining_balance": 7.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 5006,
      "expense_id": 1009,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 7.33,
      "declared_repayment": 7.33,
      "actual_repaid": 0,
      "remaining_balance": 7.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 5007,
      "expense_id": 1010,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 17,
      "declared_repayment": 17,
      "actual_repaid": 0,
      "remaining_balance": 17,
      "status": "UNSETTLED",
      "created_at": "2026-05-07T18:00:00Z"
    },
    {
      "id": 5008,
      "expense_id": 1011,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 60,
      "declared_repayment": 60,
      "actual_repaid": 0,
      "remaining_balance": 60,
      "status": "UNSETTLED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 5009,
      "expense_id": 1012,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 32,
      "declared_repayment": 32,
      "actual_repaid": 0,
      "remaining_balance": 32,
      "status": "UNSETTLED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 5010,
      "expense_id": 1015,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 10,
      "declared_repayment": 10,
      "actual_repaid": 0,
      "remaining_balance": 10,
      "status": "UNSETTLED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 5011,
      "expense_id": 1016,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 16.33,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 16.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-08T18:00:00Z"
    },
    {
      "id": 5012,
      "expense_id": 1019,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 16.33,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 16.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5013,
      "expense_id": 1021,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 16.33,
      "declared_repayment": 16.33,
      "actual_repaid": 0,
      "remaining_balance": 16.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5014,
      "expense_id": 1022,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 63.25,
      "declared_repayment": 63.25,
      "actual_repaid": 0,
      "remaining_balance": 63.25,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5015,
      "expense_id": 1028,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 60,
      "declared_repayment": 60,
      "actual_repaid": 0,
      "remaining_balance": 60,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5016,
      "expense_id": 1029,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 199,
      "declared_repayment": 199,
      "actual_repaid": 0,
      "remaining_balance": 199,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5017,
      "expense_id": 1030,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 49,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 49,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5018,
      "expense_id": 1031,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 40,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 40,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5019,
      "expense_id": 1032,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 38,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 38,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5020,
      "expense_id": 1033,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 69,
      "declared_repayment": 69,
      "actual_repaid": 0,
      "remaining_balance": 69,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5021,
      "expense_id": 1034,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 51,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 51,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5022,
      "expense_id": 1035,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 29,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 29,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5023,
      "expense_id": 1037,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 29,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 29,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5024,
      "expense_id": 1038,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 43,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 43,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5025,
      "expense_id": 1041,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 118,
      "declared_repayment": 118,
      "actual_repaid": 0,
      "remaining_balance": 118,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5026,
      "expense_id": 1043,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 11.5,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 11.5,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5027,
      "expense_id": 1044,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 80,
      "declared_repayment": 80,
      "actual_repaid": 0,
      "remaining_balance": 80,
      "status": "UNSETTLED",
      "created_at": "2026-05-09T18:00:00Z"
    },
    {
      "id": 5028,
      "expense_id": 1050,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 40,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 40,
      "status": "UNSETTLED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 5029,
      "expense_id": 1051,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 48,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 48,
      "status": "UNSETTLED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 5030,
      "expense_id": 1052,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 40,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 40,
      "status": "UNSETTLED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 5031,
      "expense_id": 1053,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 29,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 29,
      "status": "UNSETTLED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 5032,
      "expense_id": 1055,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 9,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 9,
      "status": "UNSETTLED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 5033,
      "expense_id": 1057,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 38,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 38,
      "status": "UNSETTLED",
      "created_at": "2026-05-10T18:00:00Z"
    },
    {
      "id": 5034,
      "expense_id": 1058,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 32,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 32,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5035,
      "expense_id": 1061,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 333.33,
      "declared_repayment": 333.33,
      "actual_repaid": 0,
      "remaining_balance": 333.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5036,
      "expense_id": 1062,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 55,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 55,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5037,
      "expense_id": 1064,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 8,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 8,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5038,
      "expense_id": 1066,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 8,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 8,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5039,
      "expense_id": 1067,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 10.83,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 10.83,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5040,
      "expense_id": 1069,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 10.83,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 10.83,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5041,
      "expense_id": 1070,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 13,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 13,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5042,
      "expense_id": 1072,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 13,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 13,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5043,
      "expense_id": 1073,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 38.33,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 38.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5044,
      "expense_id": 1075,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 38.33,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 38.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5045,
      "expense_id": 1076,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 59,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 59,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5046,
      "expense_id": 1078,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 24,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 24,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5047,
      "expense_id": 1079,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 5,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 5,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5048,
      "expense_id": 1081,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 5,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 5,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5049,
      "expense_id": 1082,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 5,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 5,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5050,
      "expense_id": 1084,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 5,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 5,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5051,
      "expense_id": 1085,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 26,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 26,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5052,
      "expense_id": 1087,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 26,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 26,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5053,
      "expense_id": 1088,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 10,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 10,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5054,
      "expense_id": 1090,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 10,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 10,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5055,
      "expense_id": 1091,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 89,
      "declared_repayment": 89,
      "actual_repaid": 0,
      "remaining_balance": 89,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5056,
      "expense_id": 1092,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 20,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 20,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5057,
      "expense_id": 1093,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 11.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 11.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5058,
      "expense_id": 1096,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 21,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 21,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5059,
      "expense_id": 1097,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 10.25,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 10.25,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5060,
      "expense_id": 1098,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 11.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 11.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5061,
      "expense_id": 1100,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 11.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 11.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5062,
      "expense_id": 1101,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 23,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 23,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5063,
      "expense_id": 1102,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 12.33,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 12.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5064,
      "expense_id": 1104,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 12.33,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 12.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5065,
      "expense_id": 1105,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 13.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 13.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5066,
      "expense_id": 1107,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 13.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 13.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5067,
      "expense_id": 1108,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 12.33,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 12.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5068,
      "expense_id": 1110,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 12.33,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 12.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5069,
      "expense_id": 1111,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 5,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 5,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5070,
      "expense_id": 1114,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 5,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 5,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5071,
      "expense_id": 1116,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 5,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 5,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5072,
      "expense_id": 1117,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 20,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 20,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5073,
      "expense_id": 1119,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 25,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 25,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5074,
      "expense_id": 1121,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 25,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 25,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5075,
      "expense_id": 1122,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 15,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 15,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5076,
      "expense_id": 1124,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 15,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 15,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5077,
      "expense_id": 1125,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 21.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 21.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5078,
      "expense_id": 1127,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 21.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 21.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5079,
      "expense_id": 1128,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 21.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 21.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5080,
      "expense_id": 1130,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 21.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 21.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5081,
      "expense_id": 1131,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 10,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 10,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5082,
      "expense_id": 1132,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 8,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 8,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5083,
      "expense_id": 1134,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 8,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 8,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5084,
      "expense_id": 1135,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 16.33,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 16.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5085,
      "expense_id": 1137,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 16.33,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 16.33,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5086,
      "expense_id": 1138,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 125,
      "declared_repayment": 125,
      "actual_repaid": 0,
      "remaining_balance": 125,
      "status": "UNSETTLED",
      "created_at": "2026-05-12T18:00:00Z"
    },
    {
      "id": 5087,
      "expense_id": 1141,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 25,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 25,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5088,
      "expense_id": 1143,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 19,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 19,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5089,
      "expense_id": 1145,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 210,
      "declared_repayment": 210,
      "actual_repaid": 0,
      "remaining_balance": 210,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5090,
      "expense_id": 1146,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 168,
      "declared_repayment": 168,
      "actual_repaid": 0,
      "remaining_balance": 168,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5091,
      "expense_id": 1147,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 50,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 50,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5092,
      "expense_id": 1148,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 75,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 75,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5093,
      "expense_id": 1150,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 20,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 20,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5094,
      "expense_id": 1151,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 35,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 35,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5095,
      "expense_id": 1152,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 60,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 60,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5096,
      "expense_id": 1154,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 55,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 55,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5097,
      "expense_id": 1155,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 11,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 11,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5098,
      "expense_id": 1156,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 3.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 3.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5099,
      "expense_id": 1158,
      "lender": "Winda",
      "borrower": "Syaeful",
      "amount": 3.67,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 3.67,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    },
    {
      "id": 5100,
      "expense_id": 1159,
      "lender": "Winda",
      "borrower": "Dina",
      "amount": 332,
      "declared_repayment": null,
      "actual_repaid": 0,
      "remaining_balance": 332,
      "status": "UNSETTLED",
      "created_at": "2026-05-16T18:00:00Z"
    }
  ],
  "repayments": [
    {
      "id": 9000,
      "loan_id": 5000,
      "recorded_by": "Winda",
      "amount": 350,
      "note": "Paid in cash at the condo",
      "repaid_at": "2026-05-08T20:00:00Z"
    },
    {
      "id": 9001,
      "loan_id": 5001,
      "recorded_by": "Winda",
      "amount": 50,
      "note": "Partial repayment via PromptPay",
      "repaid_at": "2026-05-17T11:00:00Z"
    },
    {
      "id": 9002,
      "loan_id": 5003,
      "recorded_by": "Winda",
      "amount": 66.67,
      "note": "Cash",
      "repaid_at": "2026-05-18T19:30:00Z"
    }
  ]
};
